# Site settings
title: Blodyavenger
header-img: img/home-bg.jpg
email: elidalidija@gmail.com
description: "Playing games and making money"
baseurl: ""
url: "http://blodyavenger.com"
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
